# WORKSPACE

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "d00f1389ee20b60018e92644e0948e16e350a7707219e7a390fb0a99b6ec9262",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.7.0/bazel-skylib-1.7.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.7.0/bazel-skylib-1.7.0.tar.gz",
    ],
)

http_archive(
    name = "rules_proto",
    sha256 = "2b0f9c9314edcf7e0937f6b68124494c58643df763fd59e37fb5dc742e0202d4",
    strip_prefix = "rules_proto-557db790e7a71993ff85bf523099dfd25060ae2f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/557db790e7a71993ff85bf523099dfd25060ae2f.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/557db790e7a71993ff85bf523099dfd25060ae2f.tar.gz",
    ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

local_repository(
    name = "io_bazel_rules_scala",
    path = "..",
)

load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")

scala_config(
    scala_version = "3.1.0",
    scala_versions = [
        "2.11.12",
        "2.12.18",
        "2.13.14",
        "3.1.0",
        "3.2.1",
        "3.3.1",
    ],
)

# loads other rules Rules Scala depends on
load("@io_bazel_rules_scala//scala:scala.bzl", "rules_scala_toolchain_deps_repositories")

rules_scala_toolchain_deps_repositories()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")

scala_register_toolchains()

load("@io_bazel_rules_scala//testing:scalatest.bzl", "scalatest_repositories", "scalatest_toolchain")

scalatest_repositories()

scalatest_toolchain()

load("@io_bazel_rules_scala//scala/scalafmt:scalafmt_repositories.bzl", "scalafmt_repositories")

scalafmt_repositories()
